package ru.ok.catalog.be.common.models

enum class MpStubCase {
    NONE,
    CATEGORY_FILTER_SUCCESS,
    CATEGORY_CREATE_SUCCESS,
    CATEGORY_READ_SUCCESS,
    CATEGORY_UPDATE_SUCCESS,
    CATEGORY_DELETE_SUCCESS,

    CLASSIFICATION_FILTER_SUCCESS,
    CLASSIFICATION_CREATE_SUCCESS,
    CLASSIFICATION_DELETE_SUCCESS,
}