package ru.ok.catalog.be.common.models

enum class MpStubCase {
    NONE,
    INVALID,

    CATEGORY_CREATE_SUCCESS,
    CATEGORY_CREATE_EXCEPTION,
    CATEGORY_CREATE_ERROR,

    CATEGORY_READ_SUCCESS,
    CATEGORY_READ_EXCEPTION,
    CATEGORY_READ_ERROR,

    CATEGORY_UPDATE_SUCCESS,
    CATEGORY_UPDATE_EXCEPTION,
    CATEGORY_UPDATE_ERROR,

    CATEGORY_DELETE_SUCCESS,
    CATEGORY_DELETE_EXCEPTION,
    CATEGORY_DELETE_ERROR,

    CATEGORY_LIST_SUCCESS,

    CLASSIFICATION_LIST_SUCCESS,
    CLASSIFICATION_CREATE_SUCCESS,
    CLASSIFICATION_DELETE_SUCCESS,
}