POST http://localhost:8081/category/create
Content-Type: application/json

{
  "type": "MpRequestCategoryCreate",
  "requestId": "req-13",
  "createData": {
    "type": "PRODUCTION",
    "code": "06.20.1",
    "title": "Добыча природного газа",
    "upRefId": "cat-50"
  }
}
###
POST http://localhost:8081/category/read
Content-Type: application/json

{
  "type": "MpRequestCategoryRead",
  "requestId": "req-13",
  "categoryId": "cat-57"
}
###
POST http://localhost:8081/category/update
Content-Type: application/json

{
  "type": "MpRequestCategoryUpdate",
  "requestId": "req-13",
  "updateData": {
    "type": "MARKETPLACE",
    "code": "06.20.1",
    "title": "Добыча природного газа+",
    "upRefId": "cat-50"
  }
}
###
POST http://localhost:8081/category/delete
Content-Type: application/json

{
  "type": "MpRequestCategoryDelete",
  "requestId": "req-13",
  "categoryId": "cat-57"
}

###
POST http://localhost:8081/category/list
Content-Type: application/json

{
  "type": "MpRequestCategoryList",
  "requestId": "req-13",
  "filterData": {
    "type": "PRODUCTION",
    "parentId": "cat-50"
  }
}


###
